### ISSUE TITLE
Install flexjs with npm on Windows 10 errors

### ISSUE THREAD

**Issue by gdeverlant** [BowlerHatLLC/vscode-nextgenas#101]
```
This license is not compatible with the Apache v2 license.
Do you want to install the designmodo fonts?
This is an optional component (y/n):  y
Downloading FlatUI
FlatUI download complete
Extracting FlatUI
FlatUI extraction complete
prompt: Apache FlexJS SDK uses the Adobe Flash Player's playerglobal.swc to build Adobe Flash applications.
The playerglobal.swc file is subject to and governed by the
Adobe Flex SDK License Agreement specified here:
http://www.adobe.com/products/eulas/pdfs/adobe_flex_software_development_kit-combined-20110916_0930.pdf,
By downloading, modifying, distributing, using and/or accessing the playerglobal.swc file
you agree to the terms and conditions of the applicable end user license agreement.

In addition to the Adobe license terms, you also agree to be bound by the third-party terms specified here:
http://www.adobe.com/products/eula/third_party/.
Adobe recommends that you review these third-party terms.

This license is not compatible with the Apache v2 license.
Do you want to download and install the playerglobal.swc?
This is a required component (y/n):  y
Downloading Adobe FlashPlayerGlobal.swc
Downloading: http://download.macromedia.com/get/flashplayer/updaters/21/playerglobal21_0.swc
Finished downloading: http://download.macromedia.com/get/flashplayer/updaters/21/playerglobal21_0.swc
prompt: Apache FlexJS SDK uses the Adobe AIR SDK to build Adobe AIR applications.
The Adobe AIR SDK is subject to and governed by the
Adobe AIR SDK License Agreement specified here:
http://www.adobe.com/products/air/sdk-eula.html.
This license is not compatible with the Apache v2 license.
Do you want to download and install the Adobe AIR SDK?This is a required component (y/n):  y
Downloading Adobe AIR from http://airdownload.adobe.com/air/win/download/21.0/AdobeAIRSDK.zip
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND airdownload.adobe.com airdownload.adobe.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
 "flexjs"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! flexjs@0.7.1 postinstall: `node dependencies/download_dependencies.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flexjs@0.7.1 postinstall script 'node dependencies/download_dependencies.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flexjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dependencies/download_dependencies.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flexjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flexjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ar.rahman\AppData\Roaming\npm-cache\_logs\2017-06-13T12_39_14_725Z-debug.log
```

**Comment by gdeverlant** [comment]
Nevermind I did that in VSCode Terminal and I think that's why it didn't work
