### ISSUE TITLE
Errors when opening Core Royale project

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#185]
When I open the Royale Core project in VS Code, I'm getting lots of errors. I'm not seeing this in other projects, and I'm not sure if there's something unique to my setup causing this.

This is what I get in the Output pane:

````
Mar 05, 2018 12:43:39 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///Apache/royale-asjs/frameworks/projects/Core/src/main/royale/CoreClasses.as",
      "languageId": "nextgenas",
      "version": 1,
      "text": "////////////////////////////////////////////////////////////////////////////////\n//\n//  Licensed to the Apache Software Foundation (ASF) under one or more\n//  contributor license agreements.  See the NOTICE file distributed with\n//  this work for additional information regarding copyright ownership.\n//  The ASF licenses this file to You under the Apache License, Version 2.0\n//  (the \"License\"); you may not use this file except in compliance with\n//  the License.  You may obtain a copy of the License at\n//\n//      http://www.apache.org/licenses/LICENSE-2.0\n//\n//  Unless required by applicable law or agreed to in writing, software\n//  distributed under the License is distributed on an \"AS IS\" BASIS,\n//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n//  See the License for the specific language governing permissions and\n//  limitations under the License.\n//\n////////////////////////////////////////////////////////////////////////////////\npackage {\n\n/**\n *  @private\n *  This class is used to link additional classes into rpc.swc\n *  beyond those that are found by dependency analysis starting\n *  from the classes specified in manifest.xml.\n */\ninternal class CoreClasses\n{\n    import org.apache.royale.core.BeadViewBase; BeadViewBase;\n    import org.apache.royale.core.ImageViewBase; ImageViewBase;\n    import org.apache.royale.core.BrowserWindow; BrowserWindow;\n\tCOMPILE::SWF\n\t{\n\t\t// import Promise; Promise;\n\t\timport org.apache.royale.core.ApplicationFactory; ApplicationFactory;\n\t\timport org.apache.royale.core.CSSShape; CSSShape;\n\t\timport org.apache.royale.core.CSSSprite; CSSSprite;\n\t\timport org.apache.royale.core.CSSTextField; CSSTextField;\n\t    import org.apache.royale.core.StyleableCSSTextField; StyleableCSSTextField;\n\t\timport org.apache.royale.core.WrappedMovieClip; WrappedMovieClip;\n\t\timport org.apache.royale.core.WrappedShape; WrappedShape;\n\t\timport org.apache.royale.core.WrappedSimpleButton; WrappedSimpleButton;\n\t\timport org.apache.royale.core.WrappedSprite; WrappedSprite;\n\t\timport org.apache.royale.core.WrappedTextField; WrappedTextField;\n\t\timport org.apache.royale.core.ByteArrayAsset; ByteArrayAsset;\n\t}\n\timport org.apache.royale.core.IBinaryImageLoader; IBinaryImageLoader;\n    import org.apache.royale.core.ItemRendererClassFactory; ItemRendererClassFactory;\n    import org.apache.royale.core.IChangePropagator; IChangePropagator;\n    import org.apache.royale.core.IAlertModel; IAlertModel;\n    import org.apache.royale.core.IBead; IBead;\n    import org.apache.royale.core.IBeadController; IBeadController;\n\timport org.apache.royale.core.IBeadLayout; IBeadLayout;\n\timport org.apache.royale.core.IBeadTransform; IBeadTransform;\n    import org.apache.royale.core.IBeadModel; IBeadModel;\n\timport org.apache.royale.core.IBeadView; IBeadView;\n\timport org.apache.royale.core.IBinding; IBinding;\n\timport org.apache.royale.core.IImageView; IImageView;\n    import org.apache.royale.core.IBinaryImage; IBinaryImage;\n\tCOMPILE::SWF\n\t{\n\t    import org.apache.royale.core.IBorderModel; IBorderModel;\n\t}\n\t\n    import org.apache.royale.core.IChild; IChild;\n    import org.apache.royale.core.IChrome; IChrome;\n    import org.apache.royale.core.IComboBoxModel; IComboBoxModel;\n    import org.apache.royale.core.IContainer; IContainer;\n\timport org.apache.royale.core.IContainerView; IContainerView;\n    import org.apache.royale.core.IContentView; IContentView;\n\timport org.apache.royale.core.IContentViewHost; IContentViewHost;\n    import org.apache.royale.core.IDataProviderItemRendererMapper; IDataProviderItemRendererMapper;\n    import org.apache.royale.core.IDataProviderVirtualItemRendererMapper; IDataProviderVirtualItemRendererMapper;\n\timport org.apache.royale.core.IDataProviderNotifier; IDataProviderNotifier;\n    import org.apache.royale.core.IBinaryImageModel; IBinaryImageModel;\n    import org.apache.royale.core.IDocument; IDocument;\n\timport org.apache.royale.core.IDragInitiator; IDragInitiator;\n    import org.apache.royale.core.IFormatBead; IFormatBead;\n    import org.apache.royale.core.IImage; IImage;\n    import org.apache.royale.core.IImageModel; IImageModel;\n    import org.apache.royale.core.IItemRendererProvider; IItemRendererProvider;\n    import org.apache.royale.core.ILayoutChild; ILayoutChild;\n\timport org.apache.royale.core.ILayoutHost; ILayoutHost;\n\timport org.apache.royale.core.ILayoutView; ILayoutView;\n\timport org.apache.royale.core.ILayoutParent; ILayoutParent;\n    import org.apache.royale.core.IListPresentationModel; IListPresentationModel;\n\timport org.apache.royale.core.IMeasurementBead; IMeasurementBead;\n    import org.apache.royale.core.IModule; IModule;\n    import org.apache.royale.core.IPanelModel; IPanelModel;\n    import org.apache.royale.core.IParent; IParent;\n    import org.apache.royale.core.IParentIUIBase; IParentIUIBase;\n    import org.apache.royale.core.IPopUp; IPopUp;\n    import org.apache.royale.core.IRangeModel; IRangeModel;\n    import org.apache.royale.core.ISWFApplication; ISWFApplication;\n\timport org.apache.royale.core.ITransformModel; ITransformModel;\n\timport org.apache.royale.core.ITransformHost; ITransformHost;\n    import org.apache.royale.core.IRollOverModel; IRollOverModel;\n\tCOMPILE::SWF\n\t{\n\t    import org.apache.royale.core.IScrollBarModel; IScrollBarModel;\n\t}\n    import org.apache.royale.core.ISelectableItemRenderer; ISelectableItemRenderer;\n    import org.apache.royale.core.ISelectable; ISelectable;\n    import org.apache.royale.core.ISelectionModel; ISelectionModel;\n    import org.apache.royale.core.IStrand; IStrand;\n\timport org.apache.royale.core.IStrandPrivate; IStrandPrivate;\n    import org.apache.royale.core.IStrandWithModel; IStrandWithModel;\n    import org.apache.royale.core.ITextModel; ITextModel;\n    import org.apache.royale.core.ITitleBarModel; ITitleBarModel;\n    import org.apache.royale.core.IToggleButtonModel; IToggleButtonModel;\n    import org.apache.royale.core.IUIBase; IUIBase;\n    import org.apache.royale.core.IValueToggleButtonModel; IValueToggleButtonModel;\n\timport org.apache.royale.core.IViewport; IViewport;\n    import org.apache.royale.core.IScrollingViewport; IScrollingViewport;\n\timport org.apache.royale.core.IViewportModel; IViewportModel;\n\tCOMPILE::SWF\n\t{\n\t\timport org.apache.royale.core.IViewportScroller; IViewportScroller;\n\t}\n    import org.apache.royale.core.SimpleStatesImpl; SimpleStatesImpl;\n\t\n\timport org.apache.royale.core.CSSClassList; CSSClassList;\n\timport org.apache.royale.core.StyleChangeNotifier; StyleChangeNotifier;\n\timport org.apache.royale.events.CustomEvent; CustomEvent;\n    import org.apache.royale.events.Event; Event;\n\timport org.apache.royale.events.CloseEvent; CloseEvent;\n\timport org.apache.royale.events.CollectionEvent; CollectionEvent;\n    import org.apache.royale.events.ProgressEvent; ProgressEvent;\n\timport org.apache.royale.events.StyleChangeEvent; StyleChangeEvent;\n    import org.apache.royale.events.EventDispatcher; EventDispatcher;\n    import org.apache.royale.events.IEventDispatcher; IEventDispatcher;\n\timport org.apache.royale.events.MouseEvent; MouseEvent;\n\timport org.apache.royale.events.KeyboardEvent; KeyboardEvent;\n\timport org.apache.royale.events.utils.KeyboardEventConverter; KeyboardEventConverter;\n\timport org.apache.royale.events.utils.MouseEventConverter; MouseEventConverter;\n\tCOMPILE::SWF\n\t{\n\t    import org.apache.royale.core.StageProxy; StageProxy;\n\t}\n\timport org.apache.royale.events.utils.KeyConverter; KeyConverter;\n\timport org.apache.royale.events.DetailEvent; DetailEvent;\n\timport org.apache.royale.events.ValueEvent; ValueEvent;\n    import org.apache.royale.events.utils.MouseUtils; MouseUtils;\n\timport org.apache.royale.events.utils.EditingKeys; EditingKeys;\n\timport org.apache.royale.events.utils.ModifierKeys; ModifierKeys;\n\timport org.apache.royale.events.utils.NavigationKeys; NavigationKeys;\n\timport org.apache.royale.events.utils.SpecialKeys; SpecialKeys;\n\timport org.apache.royale.events.utils.WhitespaceKeys; WhitespaceKeys;\n\timport org.apache.royale.events.utils.UIKeys; UIKeys;\n\timport org.apache.royale.geom.Matrix; Matrix;\n    import org.apache.royale.geom.Point; Point;\n    import org.apache.royale.geom.Rectangle; Rectangle;\n    import org.apache.royale.utils.AnimationUtil; AnimationUtil;\n    import org.apache.royale.utils.BinaryData; BinaryData;\n\timport org.apache.royale.utils.BrowserInfo; BrowserInfo;\n\tCOMPILE::SWF\n\t{\n\t    import org.apache.royale.utils.CSSBorderUtils; CSSBorderUtils;\n\t}\n\timport org.apache.royale.utils.ColorUtil; ColorUtil;\n    import org.apache.royale.utils.DisplayUtils; DisplayUtils;\n\tCOMPILE::SWF\n\t{\n\t    import org.apache.royale.utils.dbg.DOMPathUtil; DOMPathUtil;\n\t}\n\timport org.apache.royale.utils.EffectTimer; EffectTimer;\n    import org.apache.royale.utils.MixinManager; MixinManager;\n\tCOMPILE::SWF\n\t{\n\t    import org.apache.royale.utils.PNGEncoder; PNGEncoder;\n    \timport org.apache.royale.utils.SolidBorderUtil; SolidBorderUtil;\n\t\timport org.apache.royale.utils.HTMLLoader; HTMLLoader;\n\t}\n\timport org.apache.royale.utils.BrowserUtils; BrowserUtils;\n\timport org.apache.royale.utils.callLater; callLater;\n\timport org.apache.royale.utils.getParentOrSelfByType; getParentOrSelfByType;\n    import org.apache.royale.utils.CompressionUtils; CompressionUtils;\n\timport org.apache.royale.utils.Endian; Endian;\n\timport org.apache.royale.utils.JXON; JXON;\n\timport org.apache.royale.utils.MD5; MD5;\n\timport org.apache.royale.utils.OSUtils; OSUtils;\n\timport org.apache.royale.utils.PointUtils; PointUtils;\n    import org.apache.royale.utils.StringPadder; StringPadder;\n\timport org.apache.royale.utils.StringTrimmer; StringTrimmer;\n\timport org.apache.royale.utils.StringUtil; StringUtil;\n\timport org.apache.royale.utils.ObjectMap; ObjectMap;\n\timport org.apache.royale.utils.ObjectUtil; ObjectUtil;\n\timport org.apache.royale.utils.PointUtils; PointUtils;\n\timport org.apache.royale.utils.Timer; Timer;\n\timport org.apache.royale.utils.UIDUtil; UIDUtil;\n\timport org.apache.royale.utils.UIUtils; UIUtils;\n\timport org.apache.royale.utils.URLUtils; URLUtils;\n\timport org.apache.royale.utils.undo.UndoManager; UndoManager;\n\tCOMPILE::JS\n\t{\n        import org.apache.royale.events.utils.EventUtils; EventUtils;\n\t}\n\n\timport org.apache.royale.core.ClassFactory; ClassFactory;\n    import org.apache.royale.states.AddItems; AddItems;\n    import org.apache.royale.states.SetEventHandler; SetEventHandler;\n    import org.apache.royale.states.SetProperty; SetProperty;\n    import org.apache.royale.states.State; State;\n\n    import org.apache.royale.core.IDataGridModel; IDataGridModel;\n    import org.apache.royale.core.IDataGridPresentationModel; IDataGridPresentationModel;\n    import org.apache.royale.core.IDateChooserModel; IDateChooserModel;\n\timport org.apache.royale.core.ParentDocumentBead; ParentDocumentBead;\n\timport org.apache.royale.core.TransformBeadBase; TransformBeadBase;\n\timport org.apache.royale.core.TransformModel; TransformModel;\n\timport org.apache.royale.core.TransformCompoundModel; TransformCompoundModel;\n\timport org.apache.royale.core.TransformRotateModel; TransformRotateModel;\n\timport org.apache.royale.core.TransformMoveXModel; TransformMoveXModel;\n\timport org.apache.royale.core.TransformMoveYModel; TransformMoveYModel;\n\timport org.apache.royale.core.TransformScaleModel; TransformScaleModel;\n    import org.apache.royale.utils.CSSUtils; CSSUtils;\n\n    import org.apache.royale.utils.Proxy; Proxy;\n    import org.apache.royale.core.UIHTMLElementWrapper; UIHTMLElementWrapper;\n\t\n\tCOMPILE::JS\n\t{\n\t\timport org.apache.royale.core.WrappedHTMLElement ;WrappedHTMLElement;\n\t    import org.apache.royale.core.IRoyaleElement; IRoyaleElement;\n\t}\n\t//Package Level Functions\n\timport org.apache.royale.debugging.assert; assert;\n\timport org.apache.royale.debugging.assertType; assertType;\n\timport org.apache.royale.debugging.check; check;\n\t// import org.apache.royale.debugging.conditionalBreak; conditionalBreak;\n\timport org.apache.royale.debugging.notNull; notNull;\n\timport org.apache.royale.debugging.throwError; throwError;\n\n\timport org.apache.royale.utils.loadBeadFromValuesManager; loadBeadFromValuesManager;\n\n\timport org.apache.royale.utils.array.rangeCheck; rangeCheck;\n\n\timport org.apache.royale.utils.string.contains; contains;\n\timport org.apache.royale.utils.string.isWhitespace; isWhitespace;\n\timport org.apache.royale.utils.string.trim; trim;\n\timport org.apache.royale.utils.string.trimRight; trimRight;\n\timport org.apache.royale.utils.string.trimLeft; trimLeft;\n\n\timport org.apache.royale.utils.date.addDays; addDays;\n\timport org.apache.royale.utils.date.addHours; addHours;\n\timport org.apache.royale.utils.date.addMinutes; addMinutes;\n\timport org.apache.royale.utils.date.addMonths; addMonths;\n\timport org.apache.royale.utils.date.addSeconds; addSeconds;\n\timport org.apache.royale.utils.date.addYears; addYears;\n\n}\n\n}\n\n"
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:172)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:143)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.NullPointerException
	at org.apache.royale.compiler.config.Configurator.getConfigurationProblems(Configurator.java:441)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.publishConfigurationProblems(ActionScriptTextDocumentService.java:4737)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getProject(ActionScriptTextDocumentService.java:4930)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:4607)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkFilePathForAllProblems(ActionScriptTextDocumentService.java:4990)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkFilePathForProblems(ActionScriptTextDocumentService.java:4982)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didOpen(ActionScriptTextDocumentService.java:1183)
	... 16 more

````

**Comment by joshtynjala** [comment]
Thanks! I think I can see what's happening here, so it shouldn't be too difficult to fix.

As a temporary workaround, you can put JSRoyale before SWF in the targets compiler option.

**Comment by carlosrovira** [comment]
Hi, 
I'm seeing something similar in Basic project. Don't know if is related, if not I can open new issue.
Don't know if the workaround is general since I'm using maven and there's no config for targets in that project.

I was trying to get a definition from a class and I think I get this but don't know if is related to my action:

```
[Error - 19:00:02] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:210)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:146)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.NullPointerException
	at org.apache.royale.compiler.config.Configurator.getConfigurationProblems(Configurator.java:441)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.publishConfigurationProblems(ActionScriptTextDocumentService.java:4737)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getProject(ActionScriptTextDocumentService.java:4930)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:4607)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getAST(ActionScriptTextDocumentService.java:4577)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:5434)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:5398)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.actionScriptHover(ActionScriptTextDocumentService.java:2165)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.hover(ActionScriptTextDocumentService.java:469)
	... 15 more


```

**Comment by joshtynjala** [comment]
@carlosrovira In *royale-asjs/frameworks/projects/Basic/asconfig.json*, I can see that the targets compiler option is specified, and "SWF" appears before "JSRoyale". You should be able to use the same workaround.

**Comment by carlosrovira** [comment]
Hi Josh,
right, I understand now. I modified and I can confirm that it works.
thanks!
