### ISSUE TITLE
Errors when compiling Flex application

### ISSUE THREAD

**Issue by matthughes** [BowlerHatLLC/vscode-nextgenas#190]
Getting the following errors from MXML compile server when trying to compile a Flex application.  Note that I can `Run Build Task` just fine and it builds the SWF.  It is just the presentation compiler that seems to be failing.

```Generated byte code contains an operand stack underflow.```

```java.lang.NullPointerException
	at org.apache.royale.compiler.internal.tree.as.ExpressionNodeBase.isPackageReference(ExpressionNodeBase.java:244)
	at org.apache.royale.compiler.internal.tree.as.MemberAccessExpressionNode.resolve(MemberAccessExpressionNode.java:118)
	at org.apache.royale.compiler.internal.semantics.SemanticUtils.transformNameToConstantValue(SemanticUtils.java:2433)
	at org.apache.royale.compiler.internal.as.codegen.ABCGeneratingReducer.isCompileTimeConstant(ABCGeneratingReducer.java:2456)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.isCompileTimeConstant(CmcEmitter.java:90)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_MemberAccessExpressionID_2.cachedCost_4411a827(CmcEmitter.java:16871)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_MemberAccessExpressionID_2.getCostForRule_652da7d3(CmcEmitter.java:16864)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_MemberAccessExpressionID_2.getCost(CmcEmitter.java:16388)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_MemberAccessExpressionID_2.getCost(CmcEmitter.java:16428)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_MemberAccessExpressionID_2.getCostForRule_13262076(CmcEmitter.java:16912)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_MemberAccessExpressionID_2.getCost(CmcEmitter.java:16410)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_ReturnStatementID_1.getCostForRule_6293f685(CmcEmitter.java:35833)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_ReturnStatementID_1.getCost(CmcEmitter.java:35738)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.getNaryCost(CmcEmitter.java:39386)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.access$000(CmcEmitter.java:30)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_BlockID_0_n.getCost(CmcEmitter.java:10496)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_FunctionID_4.getCostForRule_1e98b88a(CmcEmitter.java:13442)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_FunctionID_4.getCost(CmcEmitter.java:13346)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_AnonymousFunctionID_1.getCostForRule_6cabf4ea(CmcEmitter.java:9630)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter$JBurgAnnotation_AnonymousFunctionID_1.getRule(CmcEmitter.java:9533)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39112)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39104)
	at org.apache.royale.compiler.internal.as.codegen.CmcEmitter.burm(CmcEmitter.java:39406)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateInstructions(ABCGenerator.java:233)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generateMXMLDataBindingGetterFunction(ABCGenerator.java:502)
	at org.apache.royale.compiler.internal.codegen.databinding.BindingCodeGenUtils.generateGetter(BindingCodeGenUtils.java:92)
	at org.apache.royale.compiler.internal.codegen.databinding.MXMLBindingDirectiveHelper.makeBindingAndGetter(MXMLBindingDirectiveHelper.java:575)
	at org.apache.royale.compiler.internal.codegen.databinding.MXMLBindingDirectiveHelper.makeBindingsAndGetters(MXMLBindingDirectiveHelper.java:475)
	at org.apache.royale.compiler.internal.codegen.databinding.MXMLBindingDirectiveHelper.getConstructorCode(MXMLBindingDirectiveHelper.java:182)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.addBindingCodeForCtor(MXMLClassDirectiveProcessor.java:2067)
	at org.apache.royale.compiler.internal.as.codegen.MXMLClassDirectiveProcessor.finishClassDefinition(MXMLClassDirectiveProcessor.java:1234)
	at org.apache.royale.compiler.internal.as.codegen.GlobalDirectiveProcessor.declareMXMLDocument(GlobalDirectiveProcessor.java:519)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:232)
	at org.apache.royale.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:188)
	at org.apache.royale.compiler.internal.as.codegen.ABCGenerator.generate(ABCGenerator.java:124)
	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleABCBytesRequest(MXMLCompilationUnit.java:199)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processABCBytesRequest(CompilationUnitBase.java:875)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$300(CompilationUnitBase.java:108)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:312)
	at org.apache.royale.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:308)
	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Here is my config:
```json
{
    "config": "flex",
    "type": "app",
	"compilerOptions": {
        "warnings": false,
        "source-path": [
            "src/main/flex",
            "common/src/main/flex"
        ],
        "library-path": [
            "target/deps"
        ],
        "output": "target/Screen.swf"
    },
    "files": [
        "src/main/flex/Screen.as"
    ]
}
```

**Comment by joshtynjala** [comment]
Can you share a minimal project that reproduces this issue? Thanks!
