### ISSUE TITLE
Embedded worker causes fatal error.

### ISSUE THREAD

**Issue by serjek** [BowlerHatLLC/vscode-nextgenas#198]
Following code causes _A fatal error occurred while checking for simple syntax problems._

```
[Embed(source="/../assets/lib/Worker.swf", mimeType="application/octet-stream")]
private static var BackgroundWorker_ByteClass:Class;
```

**Comment by joshtynjala** [comment]
Thanks! I'll take a look.

**Comment by joshtynjala** [comment]
> java.lang.NullPointerException at java.io.File.<init>(File.java:277) at org.apache.royale.utils.FilenameNormalization.normalize(FilenameNormalization.java:73)

Judging by this part of the error, it looks like there's a null path somewhere in the compiler. With that in mind, this issue may need to be fixed in the Royale compiler dependency.

**Comment by joshtynjala** [comment]
That said, I'd still like to test with your binary SWF to see if I can reproduce. You should be able to attach it in a comment on this issue, or you can send it to me privately somehow. A private message on the Starling Forums would be acceptable.

**Comment by joshtynjala** [comment]
I've discovered that if you change `var` to `const`, it should resolve this issue.

**Comment by serjek** [comment]
Cool! yes, I confirm, it resolves the issue. Although it needs to be added to wiki, I think.

**Comment by joshtynjala** [comment]
That should be a temporary workaround. I'll be pushing a commit that fixes the issue later today.
