### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#207]
I'm getting internal errors when loading a library project in 0.11.1:

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] rejected promise not handled within 1 second
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:260
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2870 [bowlerhatllc.vscode-nextgenas]Internal error.
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2870
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2870 Error: Internal error.
	at new ResponseError (/Users/harbs/.vscode/extensions/bowlerhatllc.vscode-nextgenas-0.11.1/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/Users/harbs/.vscode/extensions/bowlerhatllc.vscode-nextgenas-0.11.1/node_modules/vscode-jsonrpc/lib/main.js:430:48)
	at processMessageQueue (/Users/harbs/.vscode/extensions/bowlerhatllc.vscode-nextgenas-0.11.1/node_modules/vscode-jsonrpc/lib/main.js:258:17)
	at Immediate.<anonymous> (/Users/harbs/.vscode/extensions/bowlerhatllc.vscode-nextgenas-0.11.1/node_modules/vscode-jsonrpc/lib/main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by Harbs** [comment]
I made some changes to my asconfig.json file which made the above error go away, but I'm still getting other errors:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:211)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:178)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:183)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:92)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.Error: Unknown compiler option: additionalOptions
	at com.nextgenactionscript.asconfigc.compiler.CompilerOptionsParser.parse(CompilerOptionsParser.java:300)
	at com.nextgenactionscript.vscode.project.ASConfigProjectConfigStrategy.getOptions(ASConfigProjectConfigStrategy.java:164)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.refreshProjectOptions(ActionScriptTextDocumentService.java:1555)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getProject(ActionScriptTextDocumentService.java:4982)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:4812)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkFilePathForAllProblems(ActionScriptTextDocumentService.java:5214)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkFilePathForProblems(ActionScriptTextDocumentService.java:5206)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didOpen(ActionScriptTextDocumentService.java:1215)
	... 16 more

**Comment by joshtynjala** [comment]
>  Caused by: java.lang.Error: Unknown compiler option: additionalOptions

This is definitely a bug. It should catch this error.

However, it looks like you accidentally added additionalOptions as a property of compilerOptions. Instead, additionalOptions should be at the same level as compilerOptions. In other words, additionalOptions should be a property of the root JSON object.

**Comment by Harbs** [comment]
Ah. I missed that. Thanks! I moved it to the right place. :)

**Comment by joshtynjala** [comment]
Closed in 746d5bc14995969e0d9fcf2b7891db544561a38c
