### ISSUE TITLE
Goto definition doesn't work at all

### ISSUE THREAD

**Issue by jnpatrick99** [BowlerHatLLC/vscode-nextgenas#234]
I'm on macOS 10.12.6 and VSCode 1.24.1. Configured nextgenas.sdk.framework, don't see any errors anywhere. But Goto definition says "No definition found for '...'" whatever symbol I try. Even within the same .mxml or .as file it says the same. I tried different projects it's all the same.

I have multiple folders in my project maybe that's the case?

How to debug/fix this problem?

**Comment by joshtynjala** [comment]
Right now, the extension does not support multiple root folders in a workspace. You must open one folder only, and you must have *asconfig.json* in the root of that folder to enable code intelligence.

**Comment by jnpatrick99** [comment]
I see! Thank you for clarification.

So I put the _asconfig.json_ into the root of ActionScript project folder and _Goto definition_ started to work for that folder. 

Now I have a new problem. The nature of our project is quite complex so we cannot avoid having multiple folders. So I put the list of the files from the other folder as "files" array with their respective absolute paths into _asconfig.json_. But _Goto definition_ still doesn't work for those files (but does work for the main folder).

Is there a way to fix that too?

**Comment by jnpatrick99** [comment]
Thank you!

So I tried using _source-path_, adding both main folder and the secondary folder. After that _Goto definition_ stopped working altogether everywhere. So I added again .as & .mxml files from the second folder to "files" and it started working!

Thank you for help and support!

**Comment by jnpatrick99** [comment]
Actually I started having a new problem. After adding all these paths "Initializing ActionScript & MXML language Server..." started to crash every other time. So if I run VS Code 4 times then 2 times out of 4 it displays this message especially on MXML files:

`Jun 29, 2018 5:00:13 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 224626
	at java.lang.String.substring(String.java:1963)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.createCommandsForGenerateGetterAndSetter(CodeActionsUtils.java:96)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:67)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.codeAction(ActionScriptTextDocumentService.java:862)
	... 16 more

Jun 29, 2018 5:00:13 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 224626
	at java.lang.String.substring(String.java:1963)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.createCommandsForGenerateGetterAndSetter(CodeActionsUtils.java:96)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:67)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.codeAction(ActionScriptTextDocumentService.java:862)
	... 16 more

Jun 29, 2018 5:00:13 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1
Jun 29, 2018 5:00:13 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 3
[Error - 17:00:13] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 224626
	at java.lang.String.substring(String.java:1963)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.createCommandsForGenerateGetterAndSetter(CodeActionsUtils.java:96)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:67)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.codeAction(ActionScriptTextDocumentService.java:862)
	... 16 more

[Error - 17:00:13] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 224626
	at java.lang.String.substring(String.java:1963)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.createCommandsForGenerateGetterAndSetter(CodeActionsUtils.java:96)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:67)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.codeAction(ActionScriptTextDocumentService.java:862)
	... 16 more

Jun 29, 2018 5:00:13 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 224626
	at java.lang.String.substring(String.java:1963)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.createCommandsForGenerateGetterAndSetter(CodeActionsUtils.java:96)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:67)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.codeAction(ActionScriptTextDocumentService.java:862)
	... 16 more

[Error - 17:00:13] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 224626
	at java.lang.String.substring(String.java:1963)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.createCommandsForGenerateGetterAndSetter(CodeActionsUtils.java:96)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:67)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.utils.CodeActionsUtils.findCodeActions(CodeActionsUtils.java:79)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.codeAction(ActionScriptTextDocumentService.java:862)
	... 16 more

`

**Comment by joshtynjala** [comment]
You should need to add only the secondary folder to `source-path`. The main folder does not need to be added there too. Only your main file should go in `files`.

**Comment by joshtynjala** [comment]
I'll try to reproduce the error next week to see if I can fix it. It might be easier if you could share the contents of your *asconfig.json*.

**Comment by jnpatrick99** [comment]
Thank you! 

It may have to do with something else as well. I have a lot of _<mx:Style>_ definitions with _.css_ sources that have their own _Embeds_ (skins) pointing to a folder. So there are a lot of errors about files cannot be embedded and a lot of exceptions listed above. Looks like a path problem. I'll try to fix it on my end as well.

Here's basically the _asconfig.json_. We have two folders on the project - main root and secondary root.

```
{
  "config": "air",
  "compilerOptions": {
    "warnings": false,
    "library-path": [
      "/Path/to/Flex/sdk",
    ],    
    "target-player": "10.1",
    "source-path": [
      "/Absolute/path/to/main root src",
      "/Absolute/path/to/secondary root src",
    ],
    "output": "/Absolute/path/to/output.swf"
  },
  "application": "/Absolute/path/to/main mxml",
  "files": [
    "/Absolute/path/to any file/in/secondary root",
    "/Absolute/path/to main mxml/in/main root"
  ]
}
```

It looks like without adding any two single files from both the main and secondary root it doesn't work.

**Comment by neminovno** [comment]
@jnpatrick99 

"application": "/Absolute/path/to/main mxml",
https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json#application

**Comment by joshtynjala** [comment]
@jnpatrick99 All of the notes from @neminovno are correct.

I would add that I recommend using relative paths in *asconfig.json*, whenever possible. However, the `source-path` may be an appropriate place to use absolute paths... but it depends.

**Comment by joshtynjala** [comment]
@devilpig You don't have enough in your *asconfig.json*. Assuming it's an app, you need to add your main class to the `files` field.
