### ISSUE TITLE
Find All References: error in output window

### ISSUE THREAD

**Issue by bkodre** [BowlerHatLLC/vscode-nextgenas#273]
sep. 12, 2018 9:01:39 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.as3mxml.vscode.ActionScriptTextDocumentService.findIdentifiers(ActionScriptTextDocumentService.java:4942)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.referencesForDefinitionInCompilationUnit(ActionScriptTextDocumentService.java:3258)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.referencesForDefinition(ActionScriptTextDocumentService.java:3280)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptReferencesWithNode(ActionScriptTextDocumentService.java:3072)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptReferences(ActionScriptTextDocumentService.java:3052)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.references(ActionScriptTextDocumentService.java:765)
	... 16 more

[Error - 9:01:39 AM] Request textDocument/references failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:116)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:257)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:186)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.as3mxml.vscode.ActionScriptTextDocumentService.findIdentifiers(ActionScriptTextDocumentService.java:4942)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.referencesForDefinitionInCompilationUnit(ActionScriptTextDocumentService.java:3258)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.referencesForDefinition(ActionScriptTextDocumentService.java:3280)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptReferencesWithNode(ActionScriptTextDocumentService.java:3072)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptReferences(ActionScriptTextDocumentService.java:3052)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.references(ActionScriptTextDocumentService.java:765)
	... 16 more

**Comment by joshtynjala** [comment]
Unfortunately, I cannot seem to reproduce in v0.14.0. This issue may have been fixed coincidentally.

However, if you encounter it again, be sure to pay attention to exactly what you were trying to find a reference for. I'd like to know what was on the line of code, and exactly where the cursor was when you ran the command. Thanks!

Closing for now...
