### ISSUE TITLE
Launch: Error window when closing a release build launched via the debugger

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-nextgenas#281]
Hello Josh,

Each time I launch a release build of my application through `Debug` -> `Start Debugging` I get this error message when I close the application window:

![screen shot 09-25-18 at 04 14 pm](https://user-images.githubusercontent.com/1126990/46143783-547b9d80-c25b-11e8-937c-a0a0ec553d7e.PNG)

How could I launch my release build without trying to connect the debugger?

I'm pretty new to `Visual Studio Code`, sorry if it's a dumb question.

Best,
Aurélien

---

###  Debug console
```
Process terminated without establishing connection to debugger.
```

### Output
```
flash.tools.debugger.CommandLineException: Process terminated without establishing connection to debugger.	at flash.tools.debugger.concrete.ProcessListener.createLaunchFailureException(ProcessListener.java:197)
	at flash.tools.debugger.concrete.PlayerSessionManager.accept(PlayerSessionManager.java:833)
	at flash.tools.debugger.concrete.PlayerSessionManager.waitForConnection(PlayerSessionManager.java:244)
	at flash.tools.debugger.concrete.PlayerSessionManager.launch(PlayerSessionManager.java:234)
	at flash.tools.debugger.threadsafe.ThreadSafeSessionManager.launch(ThreadSafeSessionManager.java:87)
	at com.as3mxml.vscode.SWFDebugSession.launch(SWFDebugSession.java:471)
	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:136)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:171)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:118)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:91)
	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:63)
```

**Comment by joshtynjala** [comment]
There is currently no way to launch a SWF release build without the debugger trying to connect to it.

**Comment by Adolio** [comment]
Thanks for the clarification!

**Comment by joshtynjala** [comment]
In the upcoming v0.15 update, you will be able to choose **Debug** -> **Start Without Debugging** (Ctrl+F5) to run the SWF without connecting to the debugger.

**Comment by Adolio** [comment]
Excellent 🙂 Thanks!
