### ISSUE TITLE
NullPointerException errors in console during completion

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-nextgenas#302]
Hi Josh,

I'm working with snapshot, so maybe this error was already seen and is due to something in a work in progress. So ignore it if is nothing relevant:

I see this error in console while using:

```
nov 07, 2018 4:10:17 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
GRAVE: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.as3mxml.vscode.ActionScriptTextDocumentService.addEventMetadataToAutoCompleteMXML(ActionScriptTextDocumentService.java:4932)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.addMembersForMXMLTypeToAutoComplete(ActionScriptTextDocumentService.java:4744)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.mxmlCompletion(ActionScriptTextDocumentService.java:3250)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$completion$0(ActionScriptTextDocumentService.java:436)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 5 more
```

**Comment by joshtynjala** [comment]
No work is currently in progress.

If you can, keep the Output view open, and try to notice when this error is thrown. From the stack trace, I can tell that it's populating the completion list, and it's happening when you add an attribute to an MXML tag. So, I think what I need to know is exactly which component corresponds to the current tag when this error appears.

Thanks!

**Comment by joshtynjala** [comment]
Hmm... it appears that eventName is null in the following code:

``` java
String eventName = eventMetaTag.getAttributeValue(IMetaAttributeConstants.NAME_EVENT_NAME);
if (eventName.length() == 0)
```

This indicates that the component has `[Event]` metadata that doesn't specify a name. I can check for null easily, but you might also want to find the component in Royale that is incorrectly defining one or more of its events!

**Comment by carlosrovira** [comment]
ok Josh, I don't get the error now :?
But I know that some times Royale thinks that "org.apache.royale.events.Event" is simple "Event", but is dificult to catch. I'll try to be aware and report when I find it :)

**Comment by joshtynjala** [comment]
This error is specifically caused by bad `[Event]` metadata in a component, and it doesn't matter which `Event` class is used.

**Comment by carlosrovira** [comment]
Hi, I revised Events in the projects from Royale I use and detect only two  missing "type" attribute in Jewel Form event. Don't know if that could be a problem here or not.
Commit is e3d6f3b462d25671f95fd3f05460a4c2ec87a907

**Comment by joshtynjala** [comment]
> [Event("valid", type="org.apache.royale.events.Event")]

I think you want this instead:

``` actionscript
[Event(name="valid", type="org.apache.royale.events.Event")]
```

**Comment by carlosrovira** [comment]
Ouch! can't believe I saw type problem, but didn't see name.... 
just committed, thanks for catching that! :)
