### ISSUE TITLE
Empty test.as file in src folder creates problems

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#47]
First of four errors:
```
Internal error in syntax tree request subsystem, when generating code for: test.as: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.flex.utils.CheapArray.get(CheapArray.java:133)
	at org.apache.flex.compiler.internal.tree.as.TreeNode.getChild(TreeNode.java:67)
	at org.apache.flex.compiler.internal.units.ASCompilationUnit.handleSyntaxTreeRequest(ASCompilationUnit.java:341)
	at org.apache.flex.compiler.internal.units.CompilationUnitBase.processSyntaxTreeRequest(CompilationUnitBase.java:829)
	at org.apache.flex.compiler.internal.units.CompilationUnitBase.access$100(CompilationUnitBase.java:107)
	at org.apache.flex.compiler.internal.units.CompilationUnitBase$2$1.call(CompilationUnitBase.java:259)
	at org.apache.flex.compiler.internal.units.CompilationUnitBase$2$1.call(CompilationUnitBase.java:255)
	at org.apache.flex.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	at org.apache.flex.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
at: 1,1
```

My config files:
tasks.json:
```
{
	"version": "0.1.0",
	"command": "asconfigc",
	"isShellCommand": true,
	"args": [
		"--flexHome=F://ApacheFlex_4.15.0_FP19_AIR19"
	],
	"showOutput": "always"
}
```

asconfig.json:
```
{
    "config": "air",
    "compilerOptions": {
        "debug": true
    },
    "files":
    [
        "src/Main.mxml"
    ]
}
```
settings.json:
```
// Place your settings in this file to overwrite default and user settings.
{
    "editor.fontSize": 11,
    "nextgenas.frameworksdk": "F://ApacheFlex_4.15.0_FP19_AIR19"
}
```

**Comment by joshtynjala** [comment]
Errors are expected if the file does not contain valid content. Does the error go away once you add content to test.as?

**Comment by neminovno** [comment]
After adding content it looks the error go away.

**Comment by joshtynjala** [comment]
Okay, so the VSCode extension is working correctly. If it couldn't recover, it would have a bug. This error is actually happening in the compiler. The stack trace is definitely not the desired behavior, though. It'll need to be fixed in FlexJS.

**Comment by joshtynjala** [comment]
I fixed the stack trace issue in FlexJS. It will be included in the next release.
